# Generated by Django 2.0.4 on 2018-05-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter', '0003_auto_20180416_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.CharField(blank=True, default='', max_length=200)),
                ('firstName', models.CharField(blank=True, default='', max_length=200)),
                ('lastName', models.CharField(blank=True, default='', max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('review', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
